# Generated by Django 4.1.3 on 2023-01-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cella', models.CharField(blank=True, max_length=6)),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('seq', models.CharField(blank=True, max_length=4)),
                ('radio', models.CharField(blank=True, max_length=4)),
                ('layer', models.CharField(blank=True, max_length=10)),
                ('port', models.CharField(blank=True, max_length=1)),
                ('serial1', models.CharField(blank=True, max_length=30)),
                ('serial2', models.CharField(blank=True, max_length=30)),
                ('dlAttenuation', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
