# Generated by Django 4.1.3 on 2023-01-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sito', models.TextField()),
                ('script1', models.TextField()),
                ('script2', models.TextField()),
                ('bb1', models.CharField(blank=True, max_length=4)),
                ('bb2', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'verbose_name': 'ScriptTma',
                'verbose_name_plural': 'ScriptsTma',
            },
        ),
        migrations.AddField(
            model_name='tma',
            name='codtmpl',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
