# Generated by Django 4.1.3 on 2023-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0002_scripttma_tma_codtmpl'),
    ]

    operations = [
        migrations.AddField(
            model_name='tma',
            name='dlTrafficDelay',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tma',
            name='ulTrafficDelay',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
