# Generated by Django 4.1.3 on 2023-01-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0003_tma_dltrafficdelay_tma_ultrafficdelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='tma',
            name='rutype',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
