# Generated by Django 4.1.3 on 2023-01-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0004_tma_rutype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tma',
            name='tmatype',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
