# Generated by Django 4.1.3 on 2023-01-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0005_tma_tmatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tma',
            name='mimo',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
