# Generated by Django 4.1.3 on 2023-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0006_tma_mimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tma',
            name='subunit',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
