# Generated by Django 4.1.3 on 2023-02-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0007_tma_subunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tma',
            name='mimop',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='tma',
            name='cella',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
