# Generated by Django 4.1.3 on 2023-02-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0008_tma_mimop_alter_tma_cella'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmatype', models.CharField(blank=True, max_length=8)),
                ('subunit', models.CharField(blank=True, max_length=8)),
                ('layer', models.CharField(blank=True, max_length=8)),
                ('seqsref', models.CharField(blank=True, max_length=8)),
                ('cellafr', models.CharField(blank=True, max_length=8)),
                ('cellaly', models.CharField(blank=True, max_length=8)),
                ('mimo44', models.CharField(blank=True, max_length=8)),
                ('mimo44p', models.CharField(blank=True, max_length=8)),
                ('tsua', models.CharField(blank=True, max_length=8)),
                ('tsub', models.CharField(blank=True, max_length=8)),
                ('laye2', models.CharField(blank=True, max_length=8)),
                ('cdtmpl', models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
