# Generated by Django 4.1.3 on 2023-02-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0010_tma_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tma',
            name='port',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='tma',
            name='subunit',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
