# Generated by Django 4.1.3 on 2023-02-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0011_alter_tma_port_alter_tma_subunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tma',
            name='tsua',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='tma',
            name='tsub',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
