# Generated by Django 4.1.3 on 2023-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0012_tma_tsua_tma_tsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='tma',
            name='laye2',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
