# Generated by Django 4.1.3 on 2023-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabora', '0014_scripttma_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripttma',
            name='bb1',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='scripttma',
            name='bb2',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='scripttma',
            name='sito',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
