# Generated by Django 4.1.3 on 2023-01-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmplTma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, max_length=4)),
                ('tmpl', models.CharField(blank=True, max_length=4500)),
            ],
        ),
    ]
