# Generated by Django 4.1.3 on 2023-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutenzione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpltma',
            name='tmpl',
            field=models.TextField(blank=True, max_length=4500),
        ),
    ]
