# Generated by Django 4.2.1 on 2023-07-03 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TmplGsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, max_length=4)),
                ('tmpl', models.TextField(blank=True, max_length=4500)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptGsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sito', models.CharField(blank=True, max_length=5)),
                ('script', models.TextField()),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('bsc', models.CharField(blank=True, max_length=5)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ScriptGsm',
                'verbose_name_plural': 'ScriptsGsm',
            },
        ),
        migrations.CreateModel(
            name='AdprGsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cella', models.CharField(blank=True, max_length=6)),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('bsc', models.CharField(blank=True, max_length=5)),
                ('tg', models.CharField(blank=True, max_length=5)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
