# Generated by Django 4.2.1 on 2023-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='adprgsm',
            name='portanti',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='adprgsm',
            name='sdcch',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
