# Generated by Django 4.2.1 on 2023-11-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsm', '0002_persona_adprgsm_portanti_adprgsm_sdcch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
