# Generated by Django 4.1.3 on 2023-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('radio', models.CharField(blank=True, max_length=4)),
                ('port', models.CharField(blank=True, max_length=2)),
                ('serial', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
