# Generated by Django 4.1.3 on 2023-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altro', '0002_ret_utente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellRet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(blank=True, max_length=5)),
                ('seq', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
