# Generated by Django 4.1.3 on 2023-03-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altro', '0004_cellret_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ret',
            name='cell',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='ret',
            name='seq',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='ret',
            name='tilt',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
