# Generated by Django 4.1.3 on 2023-03-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altro', '0005_ret_cell_ret_seq_ret_tilt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ret',
            name='cell',
            field=models.CharField(blank=True, choices=[], max_length=5),
        ),
    ]
