# Generated by Django 4.1.3 on 2023-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altro', '0006_alter_ret_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ret',
            name='cell',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='ret',
            name='seq',
            field=models.CharField(blank=True, choices=[], max_length=5),
        ),
    ]
