# Generated by Django 4.1.3 on 2023-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altro', '0007_alter_ret_cell_alter_ret_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(blank=True, max_length=2)),
                ('y', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='ret',
            name='utente',
        ),
        migrations.DeleteModel(
            name='CellRet',
        ),
        migrations.DeleteModel(
            name='RET',
        ),
    ]
