# Generated by Django 4.1.3 on 2022-12-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_discussione_id_alter_post_id_alter_sezione_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adpr_lte', models.FileField(upload_to='')),
                ('adpr_gsm', models.FileField(upload_to='')),
                ('scan_1', models.FileField(upload_to='')),
                ('scan_2', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Dati',
            },
        ),
    ]
