# Generated by Django 4.1.3 on 2022-12-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_tma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tma',
        ),
    ]
