# Generated by Django 4.1.3 on 2023-01-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adpr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cella', models.CharField(blank=True, max_length=6)),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('seq', models.CharField(blank=True, max_length=4)),
                ('rusref', models.CharField(blank=True, max_length=4)),
                ('rutype', models.CharField(blank=True, max_length=10)),
                ('layer', models.CharField(blank=True, max_length=10)),
                ('mxmod', models.CharField(blank=True, max_length=2)),
                ('mimo', models.CharField(blank=True, max_length=7)),
                ('tma', models.CharField(blank=True, max_length=2)),
                ('ret', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cella', models.CharField(max_length=6)),
                ('nome_bb', models.CharField(max_length=5)),
                ('sector_equipment', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Cell',
                'verbose_name_plural': 'Cells',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('radio', models.CharField(blank=True, max_length=70)),
                ('seq', models.CharField(blank=True, max_length=4)),
                ('port', models.CharField(blank=True, max_length=1)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('unique_id', models.CharField(blank=True, max_length=30)),
                ('product_number', models.CharField(blank=True, max_length=20)),
                ('freq1tma', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_sito', models.CharField(max_length=4)),
                ('nome_sito', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Sito',
                'verbose_name_plural': 'Siti',
            },
        ),
        migrations.CreateModel(
            name='Tmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cella', models.CharField(blank=True, max_length=6)),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('seq', models.CharField(blank=True, max_length=4)),
                ('radio', models.CharField(blank=True, max_length=4)),
                ('layer', models.CharField(blank=True, max_length=10)),
                ('port', models.CharField(blank=True, max_length=1)),
                ('serial1', models.CharField(blank=True, max_length=30)),
                ('serial2', models.CharField(blank=True, max_length=30)),
                ('dlAttenuation', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ValoriTma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productNumber', models.CharField(blank=True, max_length=20)),
                ('layer', models.CharField(blank=True, max_length=2)),
                ('dlAttenuation', models.CharField(blank=True, max_length=4)),
                ('dlTrafficDelay', models.CharField(blank=True, max_length=4)),
                ('ulTrafficDelay', models.CharField(blank=True, max_length=4)),
                ('tma_type', models.CharField(blank=True, max_length=4)),
                ('subunit', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb', models.CharField(max_length=5)),
                ('radio', models.CharField(max_length=3)),
                ('productNumber', models.CharField(max_length=5)),
                ('freqTx', models.CharField(max_length=5)),
                ('serial_number', models.CharField(max_length=5)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importa.cell')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='sito_appartenenza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importa.sito'),
        ),
    ]
