# Generated by Django 4.1.3 on 2023-01-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tma',
            name='cell',
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='Sito',
        ),
        migrations.DeleteModel(
            name='Tma',
        ),
    ]
