# Generated by Django 4.1.3 on 2023-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importa', '0002_remove_tma_cell_delete_cell_delete_sito_delete_tma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tmas',
        ),
    ]
