# Generated by Django 4.1.3 on 2023-03-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importa', '0005_scan_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpr',
            name='atdl',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='adpr',
            name='rtel',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
