# Generated by Django 4.1.3 on 2023-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importa', '0006_adpr_atdl_adpr_rtel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpr',
            name='tilt',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
