# Generated by Django 4.2.1 on 2024-03-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importa', '0007_adpr_tilt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpr',
            name='ret',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
