# Generated by Django 4.2.1 on 2024-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importa', '0008_alter_adpr_ret'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpr',
            name='sistema',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
