# Generated by Django 4.1.3 on 2023-03-19 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('radio', models.CharField(blank=True, max_length=4)),
                ('port', models.CharField(blank=True, max_length=2)),
                ('serial', models.CharField(blank=True, max_length=30)),
                ('cell', models.CharField(blank=True, max_length=5)),
                ('seq', models.CharField(blank=True, max_length=5)),
                ('tilt', models.CharField(blank=True, max_length=5)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CellRet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(blank=True, max_length=5)),
                ('seq', models.CharField(blank=True, max_length=5)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
