# Generated by Django 4.1.3 on 2023-03-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ret',
            name='cell',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
