# Generated by Django 4.1.3 on 2023-03-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0002_alter_ret_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellret',
            name='cell',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
