# Generated by Django 4.1.3 on 2023-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0003_alter_cellret_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellret',
            name='master',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
