# Generated by Django 4.1.3 on 2023-03-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0004_cellret_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellret',
            name='mimo',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='cellret',
            name='master',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
