# Generated by Django 4.1.3 on 2023-04-02 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ret', '0005_cellret_mimo_alter_cellret_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sito', models.CharField(blank=True, max_length=10)),
                ('sttr', models.CharField(blank=True, max_length=10)),
                ('seceq', models.CharField(blank=True, max_length=10)),
                ('banda', models.CharField(blank=True, max_length=10)),
                ('serial', models.CharField(blank=True, max_length=10)),
                ('radctrl', models.CharField(blank=True, max_length=10)),
                ('porta', models.CharField(blank=True, max_length=10)),
                ('prog', models.CharField(blank=True, max_length=10)),
                ('eltlt', models.CharField(blank=True, max_length=10)),
                ('usrlbl', models.CharField(blank=True, max_length=10)),
                ('tmplt', models.CharField(blank=True, max_length=10)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
