# Generated by Django 4.1.3 on 2023-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0006_swapmatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindBanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(blank=True, max_length=10)),
                ('banda', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
