# Generated by Django 4.1.3 on 2023-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0007_findbanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findbanda',
            name='banda',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
