# Generated by Django 4.1.3 on 2023-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0008_alter_findbanda_banda'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmplRet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, max_length=4)),
                ('tmpl', models.TextField(blank=True, max_length=4500)),
            ],
        ),
    ]
