# Generated by Django 4.1.3 on 2023-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0009_tmplret'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellret',
            name='ordine',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
