# Generated by Django 4.1.3 on 2023-04-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0010_cellret_ordine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellret',
            name='ordine',
        ),
    ]
