# Generated by Django 4.1.3 on 2023-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0011_remove_cellret_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellret',
            name='ordine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
