# Generated by Django 4.1.3 on 2023-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0012_cellret_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ret',
            name='ordine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
