# Generated by Django 4.1.3 on 2023-04-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0013_ret_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellret',
            name='radio',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
