# Generated by Django 4.1.3 on 2023-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0014_cellret_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellret',
            name='bb',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
