# Generated by Django 4.1.3 on 2023-04-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ret', '0015_cellret_bb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sito', models.CharField(blank=True, max_length=5)),
                ('script1', models.TextField()),
                ('script2', models.TextField()),
                ('bb1', models.CharField(blank=True, max_length=5)),
                ('bb2', models.CharField(blank=True, max_length=5)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ScriptRet',
                'verbose_name_plural': 'ScriptsRet',
            },
        ),
    ]
