# Generated by Django 4.1.3 on 2023-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0016_scriptret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapmatrix',
            name='banda',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
