# Generated by Django 4.1.3 on 2023-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0017_alter_swapmatrix_banda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellret',
            name='tilt',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
