# Generated by Django 4.1.3 on 2023-05-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0018_cellret_tilt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapmatrix',
            name='serial',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
