# Generated by Django 4.2.1 on 2023-11-17 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ret', '0019_alter_swapmatrix_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRetLog',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('sito', models.CharField(blank=True, max_length=5)),
                ('bb', models.CharField(blank=True, max_length=5)),
                ('script', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ScriptRetLog',
                'verbose_name_plural': 'ScriptsRetLogs',
            },
        ),
    ]
