# Generated by Django 4.2.1 on 2024-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0020_scriptretlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellret',
            name='sistema',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='swapmatrix',
            name='sistema',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
