# Generated by Django 4.2.1 on 2024-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ret', '0021_cellret_sistema_swapmatrix_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='ret',
            name='sistema',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
