from django.urls import path
from . import views

urlpatterns = [
        path(
            "importa-adpr/", 
            views.importAdpr, 
            name="importa_adpr"
        ),  
        path(
            "importa-scan/", 
            views.importScan, 
            name="importa_scan"
        ),                                     
        path("create-view/", 
            views.create_view, 
            name="create_view"
        ),
        path("create-scan-view/", 
            views.create_scan_view, 
            name="create_scan_view"
        ),        
        path("list-view/", 
            views.list_view, 
            name="list_view"
        ),
        path("list-view2/", 
            views.list_view2, 
            name="list_view2"
        ),        
        path("scan-view/", 
            views.scan_view, 
            name="scan_view"
        ),   
        path("scan-view2/", 
            views.scan_view2, 
            name="scan_view2"
        ),               
        path('<id>', 
            views.detail_view 
        ),
        path('<id>/update/', 
            views.update_view,
            name="update" 
        ),
        path('<id>/update_scan/', 
            views.updateScan_view,
            name="update_scan" 
        ),        
        path('<id>/delete/', 
            views.delete_view,
            name="delete"  
        ),
        path('<id>/deletescan/', 
            views.deletescan_view,
            name="deletescan"  
        ),        
        path('deleteall/', 
            views.deleteall_view,
            name="deleteall"  
        ), 
        path('deleteallscan/', 
            views.deleteallscan_view,
            name="deleteallscan"  
        ), 
        path("", 
            views.list_view 
        ),
        path('importa-valoritma/', 
            views.importValotiTma, 
            name="importa_valoritma"
        ),         
]